### PR TITLE
option to disable redis

### PR DESCRIPTION
**Pull request by TzachiSh**

### CODE REVIEW

**Comment by bodamat** [comment]
Unfortunately, I don't understand the point of this method to disable Redis. The best option to disable Redis completely is just to pass `redis: null` in the option or set `useRedis: false`, but this is to disable Redis for queries

**Comment by TzachiSh** [comment]
The option redis: null not working 
The package tries to connect redis no meter what...

**Comment by bodamat** [comment]
ah, sorry. I will check this tomorrow. I don't want to keep Redis disabled by default, because in most cases it's needed

**Comment by bodamat** [comment]
I checked and the null value in Redis works correctly. Maybe the code is not apparent, unfortunately.

**Comment by bodamat** [comment]
Thanks a lot for the suggestion. I fixed it in the latest commits

**Pull request closed without merging**
